<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kubernetesModel" nsURI="org.palladiosimulator.kubernetesModel"
    nsPrefix="k8smodel">
  <eSubpackages name="resourceenvironment" nsURI="org.palladiosimulator.kubernetesModel.resourceenvironment"
      nsPrefix="resenv">
    <eClassifiers xsi:type="ecore:EClass" name="KubernetesNode" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMasterNode" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBigInteger"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RunningPodNestedResourceContainer"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectorDeploymentReference"
          eType="#//k8sconcepts/Deployment" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="repository" nsURI="org.palladiosimulator.kubernetesModel.repository"
      nsPrefix="repo">
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/CompositeComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="standardLimit" eType="#//k8sconcepts/K8sStandardRequestLimit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="standardRequest" eType="#//k8sconcepts/K8sStandardRequestLimit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pod" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//subsystem/SubSystem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Containers" upperBound="-1"
          eType="#//repository/Container"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="k8sconcepts" nsURI="org.palladiosimulator.kubernetesModel.k8sconcepts"
      nsPrefix="k8s">
    <eClassifiers xsi:type="ecore:EClass" name="Deployment" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="replicas" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PodReference" eType="#//repository/Pod"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="AllocatedPods" upperBound="-1"
          eType="#//resourceenvironment/RunningPodNestedResourceContainer" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractK8sRequestLimit" abstract="true"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="K8sStandardRequestLimit" eSuperTypes="#//k8sconcepts/AbstractK8sRequestLimit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu" upperBound="-1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" upperBound="-1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBigInteger"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="K8sAdditionalRequestLimit" eSuperTypes="#//k8sconcepts/AbstractK8sRequestLimit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" upperBound="-1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequestsLimitsRepository">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requestsLimitsRepo" ordered="false"
          upperBound="-1" eType="#//k8sconcepts/AbstractK8sRequestLimit" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Deployments">
      <eStructuralFeatures xsi:type="ecore:EReference" name="DeploymentInstances"
          upperBound="-1" eType="#//k8sconcepts/Deployment" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="system" nsURI="org.palladiosimulator.kubernetes.kubernetesModel.system"
      nsPrefix="sys">
    <eClassifiers xsi:type="ecore:EClass" name="DeploymentAssembly" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Deployment" eType="#//k8sconcepts/Deployment"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
