<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kubernetesModel">
  <eClassifiers xsi:type="ecore:EClass" name="Container1" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/CompositeComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="request"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eSubpackages name="system"/>
  <eSubpackages name="resourceenvironment">
    <eClassifiers xsi:type="ecore:EClass" name="KubernetesNode" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="WorkerNode" eSuperTypes="#//resourceenvironment/KubernetesNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="MasterNode" eSuperTypes="#//resourceenvironment/KubernetesNode"/>
  </eSubpackages>
  <eSubpackages name="repository">
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/CompositeComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pod" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/CompositeComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Containers" upperBound="-1"
          eType="#//repository/Container"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="allocation"/>
  <eSubpackages name="kubernetesconcepts">
    <eClassifiers xsi:type="ecore:EClass" name="Deployment"/>
    <eClassifiers xsi:type="ecore:EClass" name="Request">
      <eStructuralFeatures xsi:type="ecore:EReference" name="CPURequest" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ProcessingResourceSpecification"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MemoryRequest" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/HDDProcessingResourceSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Limit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="CPULimit" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ProcessingResourceSpecification"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MemoryLimit" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/HDDProcessingResourceSpecification"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
